training:
  from_ckpt: '/home/chenjiehao/projects/Neural-Simulator/ckpt/vsdreamer/cheetah/base/td_mpc_02191604/ckpt_240M.pth'
  training_stage: -1
  seed: 18829
  lr: 0.0001
  num_epochs : 10000000
  t : 0.02
  batch_size : 50000
  save_path : 'ckpt/vsdreamer/cheetah/td_mpc'
  keep_top : 5
model:
  ## model_param:
  q_dim : 9
  v_dim : 9
  action_dim : 6
  real_t : 0.01
  activation : 'softplus' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 3
  m_network_width : 64
  ### B Module:
  b_hidden_block_num : 3
  b_network_width : 64
  ### action_module_param:
  act_network_type: 'MLP' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 3
  act_network_width : 32
  ### correctors:
  crt_num : 1
  crt_hidden_block_num : 5
  crt_network_width : 64
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/cheetah/tdmpc_train_2/cheetah-run.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/cheetah/tdmpc_train_2/cheetah_run_test.npz'
