training:
  training_stage: -1
  seed: 45
  lr: 0.004
  num_epochs : 1000000000
  t : 0.002
  batch_size : 50000
  save_path : '/home/chenjiehao/projects/Neural-Simulator/ckpt/myosuite/finger_myo/'
  keep_top : 5
model:
  ## model_param:
  v_dim : 4
  action_dim : 5
  real_t : 0.002
  activation : 'softplus' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 3
  m_network_width : 64
  ### B Module:
  b_hidden_block_num : 3
  b_network_width : 64
  ### action_module_param:
  act_network_type: 'ResidualNetwork' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 3
  act_network_width : 32
  ### correctors:
  crt_num : 1
  crt_hidden_block_num : 3
  crt_network_width : 64
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/myosuite/finger/motorfinger_train.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/myosuite/finger/motorfinger_test.npz'

# python train.py --config /home/chenjiehao/projects/Neural-Simulator/configs/reacher_0crts_int.yaml --device cuda:7
# 4-10