training:
  training_stage: -1
  seed: 42
  lr: 0.001
  num_epochs : 1000000000
  t : 0.002
  batch_size : 50000
  save_path : '/home/chenjiehao/projects/Neural-Simulator/ckpt/vsdreamer/panda/noise/'
  keep_top : 5
model:
  ## model_param:
  v_dim : 9
  action_dim : 8
  real_t : 0.002
  activation : 'softplus' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 3
  m_network_width : 64
  ### B Module:
  b_hidden_block_num : 3
  b_network_width : 64
  ### action_module_param:
  act_network_type: 'MLP' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 1
  act_network_width : 32
  ### correctors:
  crt_num : 3
  crt_hidden_block_num : 5
  crt_network_width : 128
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/panda/noise/noisy_data_0.001.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/panda/poisson/panda_poisson_test.npz'
