training:
  training_stage: -1
  seed: 188299
  lr: 0.004
  num_epochs : 10000000
  t : 0.005
  batch_size : 50000
  save_path : 'ckpt/hopper_contrast_experiments/exp1'
  keep_top : 5
model:
  ## model_param:
  v_dim : 7
  action_dim : 4
  real_t : 0.005
  activation : 'softplus' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 3
  m_network_width : 64
  ### B Module:
  b_hidden_block_num : 3
  b_network_width : 64
  ### action_module_param:
  act_network_type: 'MLP' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 3
  act_network_width : 32
  ### correctors:
  crt_num : 2
  crt_hidden_block_num : 5
  crt_network_width : 128
data:
  ## data_path:
  train_data_path : 'data/hopper_random'
  test_data_path : 'data/hopper_random_test'
