training:
  training_stage: -1
  seed: 188298
  lr: 0.004
  num_epochs : 1000000000
  t : 0.002
  batch_size : 50000
  save_path : '/home/chenjiehao/projects/Neural-Simulator/ckpt/vsdreamer/go2/noise'
  keep_top : 5
model:
  ## model_param:
  q_dim : 19
  v_dim : 18
  action_dim : 12
  quat_config : [3,22]
  real_t : 0.002
  activation : 'softplus' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 3
  m_network_width : 128
  ### B Module:
  b_hidden_block_num : 3
  b_network_width : 128
  ### action_module_param:
  act_network_type: 'MLP' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 1
  act_network_width : 128
  ### correctors:
  crt_num : 2
  crt_hidden_block_num : 5
  crt_network_width : 128
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/go2/noise/noisy_data_0.001.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/go2/poisson/go2_poisson_test.npz'


# 4-1  with o
# 4-2  without o



