training:
  training_stage: -1
  seed: 188299
  lr: 0.004
  num_epochs : 1000000000
  t : 0.002
  batch_size : 50000
  save_path : '/home/chenjiehao/projects/Neural-Simulator/ckpt/myosuite/hand_motor/'
  keep_top : 5
model:
  ## model_param:
  v_dim : 23
  action_dim : 39
  real_t : 0.002
  activation : 'softplus' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 5
  m_network_width : 256
  ### B Module:
  b_hidden_block_num : 5
  b_network_width : 256
  ### action_module_param:
  act_network_type: 'MLP' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 3
  act_network_width : 256
  ### correctors:
  crt_num : 2
  crt_hidden_block_num : 5
  crt_network_width : 128
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/myosuite/hand/myohand_train_motor.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/myosuite/hand/myohand_test_motor.npz'
