training:
  training_stage: -1
  seed: 188299
  lr: 0.001
  num_epochs : 10000000
  t : 0.01
  batch_size : 50000
  save_path : 'ckpt/vsdreamer/cheetah/ms/int_noode/dopri5'
  keep_top : 5
model:
  ## model_param:
  q_dim : 9
  v_dim : 9
  action_dim : 6
  real_t : 0.01
  activation : 'swish' #['softplus','atan','relu']
  ### M Module:
  m_hidden_block_num : 5
  m_network_width : 128
  ### B Module:
  b_hidden_block_num : 5
  b_network_width : 128
  ### action_module_param:
  act_network_type: 'MLP' #['ResidualNetwork','MLP','None']
  act_hidden_block_num : 5
  act_network_width : 32
  ### correctors:
  crt_num : 1
  crt_hidden_block_num : 5
  crt_network_width : 64

  is_ode: True
  manually_int_q: True
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/cheetah/random/cheetah_random.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/cheetah/random/cheetah_random_test.npz'
