training:
  training_stage: -1
  seed: 188299
  lr: 0.001
  num_epochs : 10000000
  t : 0.01
  batch_size : 50000
  save_path : 'ckpt/vsdreamer/cheetah/ms/int_noode/rk4_atten'
  keep_top : 5
model:
  #  model_param:
  q_dim : 9
  v_dim : 9
  action_dim : 6
  real_t : 0.01
  activation : 'swish' #['softplus','atan','relu','swish']
  is_ode: True
  integrator: rk4
  dynamic_model_type:  'attention'  #['rigid_body','resnet']
  ### dynamics:
  attn_ffn_hidden_dim: 64
  attn_block_num: 5
  attn_embed_dim: 8
  attn_heads_num: 1
  manually_int_q: True
data:
  ## data_path:
  train_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/cheetah/random/cheetah_random.npz'
  test_data_path : '/home/chenjiehao/projects/Neural-Simulator/data/cheetah/random/cheetah_random_test.npz'
